<?php
/**
 * Created by TeraBoxX.
 * User: tommy
 * Date: 1/13/2018
 * Time: 10:37 PM
 */

include_once APPLICATION_DIR."configuration/constants.php";

$config['configuration'] = array(
	'default' => array(
		'app_name' => 'TeraBlaze',
		'app_id' => 'tb',

		'environment' => 'development',

		/*
		 *******************************************************************************
		 * Base Site URL
		 *******************************************************************************
		 *
		 * URL to your TeraBlaze application root. Typically this will be your base URL,
		 * WITHOUT a trailing slash:
		 *
		 *	http://example.com
		 *
		 * WARNING: You MUST set this value! If you don't,
		 * TeraBlaze will try to guess the value using $_SERVER variables
		 * but it is generally a good practice to set it
		 *
		 */
		'base_url' => '',

		/*
		 *************************************************************************
		 * Index File
		 *************************************************************************
		 *
		 * Typically this will be your index.php file, unless you've renamed it to
		 * something else. If you are using mod_rewrite to remove the page set this
		 * variable so that it is blank.
		 *
		 */
		'index_script' => 'index.php',

		/*
		 ****************************************************************************
		 * URI PROTOCOL
		 ****************************************************************************
		 *
		 * This item determines which server global should be used to retrieve the
		 * URI string.  The default setting of 'REQUEST_URI' works for most servers.
		 * If your links do not seem to work, try one of the other delicious flavors:
		 *
		 * 'REQUEST_URI'    Uses $_SERVER['REQUEST_URI']
		 * 'QUERY_STRING'   Uses $_SERVER['QUERY_STRING']
		 * 'PATH_INFO'      Uses $_SERVER['PATH_INFO']
		 *
		 * WARNING: If you set this to 'PATH_INFO', URIs will always be URL-decoded!
		 */
		'uri_protocol' => 'PATH_INFO',

		/*
		 ***************************************************************************
		 * URL suffix
		 ***************************************************************************
		 *
		 * This option allows you to add a suffix to all URLs generated by TeraBlaze
		 *
		 */
		'url_suffix' => '',

		/*
		 *************************************************************************
		 * Default CONTROLLER and ACTION
		 *************************************************************************
		 */
		'default_controller_action' => 'home/index',

		/*
		 *************************************************************************
		 * Default PROTOCOL
		 *************************************************************************
		 */
		'default_protocol' => 'http',

		/*
		 *************************************************************************
		 * Virtual location
		 *************************************************************************
		 * 
		 *
		 */
		'virtual_location' => '/',
	),
);